# Generated by Django 4.2.21 on 2025-05-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('no', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('images', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('img', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.TextField(max_length=20, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='images/')),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='images/')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('img', models.FileField(upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('discount', models.CharField(max_length=10)),
                ('discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nari',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('discount', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Oh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='P1',
            fields=[
                ('id', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='images/')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='P2',
            fields=[
                ('id', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='images/')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('images', models.FileField(upload_to='images/')),
            ],
        ),
    ]
